### ISSUE TITLE
LVDS DIO rev2  Errata

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#242]
- [ ] Fix ordering of LEDs to match RJ45 connectors
- [ ] Zero-index all channels
- [ ] Invert/fix footprints of 0603 LEDs
- [ ]  Please remove the annotation "This module connects to Kasli ..." and replace it with something like "EEM connector: IO are LVDS, I2C is 3V3 LVCMOS, P3V3_MP up to 20mA, P12V up to 1A."
- [ ] Schematic needs a tidy up:
  - Remove annotations saying "ADD TVS!!!" (do we need to add TVS?)
  - First page should be title page, not LVDS buffer page
- [ ] Run off 2V5 to save power?
- [ ] Check output noise, do we need a bigger capacitor/LC filter?
- [ ] Large clear note on the schematic + silk + docs that live switching of directions may result in damage.
- [ ] Silk + schematic + panel should be "v1.x" not "rev1.x"

**Comment by hartytp** [comment]
@gkasprow Sorry for not picking up these issues in the previous design review!

**Comment by gkasprow** [comment]
I noticed them doing panel design. This should have been done in rev1 but there is so much work...

**Comment by hartytp** [comment]
No worries Greg -- you guys are tackling an intimidating number of hardware designs at the same time and making great progress, so a few minor things are bound to slip through!

These issues are only cosmetic and don't affect the boards' functionality. In any case, these boards are still prototypes, rather than production, so these kind of minor issues are expected :) 

At this point, I think the top priority is getting prototype hardware delivered to a few labs for thorough testing. We can always fix these small issues in rev2.

**Comment by jordens** [comment]
What does the QC sticker actually mean? On my 3U_DIO_RJ45 two pins of the RJ45 cage were not soldered.

**Comment by gkasprow** [comment]
@jordens could you take photo of this and send me? I'll ask Technosystem about it. QC means that it passed functional test.

**Comment by jordens** [comment]
Out of curiosity: what functional tests are being done?

I already soldered it myself. Photos of that probably won't help. Bottom corner of the cage.

![image](https://user-images.githubusercontent.com/1338946/30969197-f471d43a-a461-11e7-8b17-72adab5d85f7.png)

**Comment by gkasprow** [comment]
We tested propagation of signal through all ports in both directions and power consumption. Technosystem does AOI tests so we will investigate it.

**Comment by jordens** [comment]
Ok. Those tests sound good. Thanks!

**Comment by marmeladapk** [comment]
_Migrated to sinara-hw/DIO_RJ45#1_
