### ISSUE TITLE
stress on AFE from SMA

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#263]
1. SMA barrel on AFEs is long enough that the threads extend to the back side of the RTM panel. If user tightens nut on SMA barrel, SMPs and DIO header are stressed. Possible solutions:
 - Use SMA with a gap between threads and PCB end of connector (mechanically the best option)
 - advise users to /not/ use SMA nuts. *add note on schematics and documentation*.

2. Attachment of a SMA cable will put stress on SMPs and DIO header. This will be particularly bad if we don't use nuts on the AFE SMAs. Possible solutions:
  -add standoffs to secure the AFEs to the RTM.  (need to be included in the BOM)
  - advise users on recommended SMA torque (include in manual)

**Comment by dhslichter** [comment]
For the time being, is there enough room to put an SMA nut on the inside of the panel as well as outside?  This is a standard way of addressing this issue.  In the long term having mechanical standoffs connecting RTM to AFE cards sounds good, if there is space.

**Comment by jordens** [comment]
there need to be nuts on the inside in any case for the longer connectors because of length and "flush-ness"
.

**Comment by gkasprow** [comment]
@dhslichter @jordens @jbqubit  the RTM is missing machined plastic panel which takes care about SMA isolation and  positioning of SMAs in the panel holes. It also reduces stress on AFE. We planned to use dedicated isolation washers but their assembly would be painful for so many SMAs.

**Comment by dhslichter** [comment]
@gkasprow ack, is this documented in the wiki or in the repository?

**Comment by gkasprow** [comment]
@dhslichter Design of such panel is on a way. I was waiting for MTCA panels to check how it fits. There was discussion about it but I cannot find it right now.

**Comment by gkasprow** [comment]
@dhslichter design is ready. 
![obraz](https://user-images.githubusercontent.com/4325054/29905647-3add78a6-8e10-11e7-9766-8f9a77f84988.png)
![obraz](https://user-images.githubusercontent.com/4325054/29905658-48cf00c4-8e10-11e7-8be7-165e2699e34b.png)

**Comment by gkasprow** [comment]
[here](https://github.com/m-labs/sinara/tree/master/MECH/PANELS) are the files

**Comment by jbqubit** [comment]
@gkasprow Is there room for standoff’s between AFEs and RTM? There are holes on both PCBs to support this. Some ICs look very close to where standoffs would attach in the current layout...

**Comment by gkasprow** [comment]
Yes, each AFE is positioned using 4 standoffs.
The holes are 2.55mm, pad is 4.55mm in diameter.
we will use these standoffs
http://www.farnell.com/datasheets/1231941.pdf?_ga=2.141285745.271167733.1504158512-162313899.1464604133

**Comment by jbqubit** [comment]
I looked to check if the standoffs are in the Allaki AFE BOM but can't find a BOM. Doesn't look like there are BOMs for the EEM designs but not Sayma-related designs.

**Comment by gkasprow** [comment]
@jbqubit I added the BOM files for Sayma/Metlino boards

**Comment by jbqubit** [comment]
@gkasprow Thanks for adding the BOMs. :)

**Comment by hartytp** [comment]
Not relevant now that we're planning to move to an FMC form-factor for the next version (if the AFE has its own FP, this isn't an issue anymore).
