### ISSUE TITLE
BaseMod rev1 errata

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/sinara#269]
- [ ] replace AD8363ACPZ-WP  with AD8363ACPZ-R7CT-ND 
- [ ] replace ADT7420UCPZ-R2 with ADT7420UCPZ-RL7TR-ND
- [ ] This board has a lot of pads for potential matching components. At the frequency this AFE is designed to operate at, these are unnecessary. Please remove them from the schematic + layout to simplify things and save space (the boards are quite cramped atm).
- [ ] We do not need an input path that bypasses the InAmp. Please remove these solder jumpers.
- [ ] Zero-index everything (silk, schematic, panel)
- [ ] Make sure that we're using the cheapest acceptable substrates. e.g. FR408 on the RF layer, FR4 everywhere else.
- [ ] Should we add inductors on the +-12V to filter them (these are generated by SMPSs on Sayma and do not have LDOs on BaseMod so may contain high-frequency noise).
- [ ] Add version number to schematic
- [ ] Text is upside down for C4, R40, R42, C63 (although, these are being dropped from V2.0)
- [ ] should probably have a power budget on the schematic like the ones for the EEMs.
- [ ] Input/output connector caps should be 2*1nF on each connector. (Why are there three caps on the input SMA?)
- [ ] add current limiting resistor for attenuator output

**Comment by sbourdeauducq** [comment]
As explained in detail several times already, it would be better to have one issue for each item instead of one big errata, and use milestones and labels.

**Comment by jbqubit** [comment]
@gkasprow asked in email
>To do tests of Allaki, I'd need sine wave at the DAC output. The sooner, the better.
What about clocking DAC from 100MHz source?

**Comment by jbqubit** [comment]
- Allaki as-shipped to UMD do not have serial numbers. Please add serial numbers so end-users, WUT and Technosystem can track.

- back-side silkscreen double printing 
![image](https://user-images.githubusercontent.com/20543958/32899696-a8074246-cab9-11e7-8832-37a37eec96a1.png)

- As-shipped to UMD insulating front-panel missing. @gkasprow is sending the right panel. Photo from @gkasprow below so everybody can see what this will look like. 
![image](https://user-images.githubusercontent.com/20543958/32899955-502dbc0c-caba-11e7-9e0d-0173a82f740a.png)

**Comment by hartytp** [comment]
Does anyone object to removing the power detector from BaseMod v1.1? cf #397

**Comment by dhslichter** [comment]
The point of the power detector is to noise-eat at the output of the DACs.  What is it costing us?

**Comment by hartytp** [comment]
Yes, but only when the switch is off, and only via the 24-bit ADC.

Main cost is space: as @sbouhabib pointed out elsewhere, this is the largest component on BaseMod and fitting it on was actually quite challenging. If we remove it then we can make the layout a bit less tight.

Not a huge deal, but it's not totally cost free so unless you **really** plan to use it then we should scrap it.

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/BaseMod#6
