### ISSUE TITLE
BaseMod insertion-removal, inter-BaseMod interference

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#367]
Allaki can't be independently removed due to board-board interference of cutouts to accommodate SMA connectors. Sayma_RTM v1.0 and Allaki v0.1. This does not interfere with testing but should not be the case for final production. 

Here are the cutouts. 
![image](https://user-images.githubusercontent.com/20543958/32900144-c3175980-caba-11e7-9de8-ed1b422c575b.png)

Cutouts interfere with board removal. 
![image](https://user-images.githubusercontent.com/20543958/32901319-8ac5b894-cabd-11e7-86e7-a5b3215113da.png)

- A can be removed
- removal of D requires first removing A then B then C 

Tolerance is such that there is zero gap between Allaki at the location of the cutouts.

**Comment by gkasprow** [comment]
@jbqubit this is known bug, already on the list.

**Comment by gkasprow** [comment]
@jbqubit Sorry, I mixed things. This "feature" was not known before. Thanks!

**Comment by hartytp** [comment]
Not relevant any more. Next version will have an FMC footprint without these cutouts.
