### ISSUE TITLE
Sayma_AMC IPMI

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#370]
I have a MCH-Baisc v3.5 in same uTCA.4 crate as Sayma_AMC. Sayma_AMC is installed in slot AMC1. Here's what I see. 

![screenshot from 2017-11-16 13 58 07](https://user-images.githubusercontent.com/20543958/32910061-39abad42-cad6-11e7-95b2-342e5ab59c20.png)

**Comment by gkasprow** [comment]
There is no IPMI-compilant firmware in the CPU right now. Just switch on the supply manually.

**Comment by jbqubit** [comment]
Do I recall correctly that Creotech is working on this? It's a variation of an open source firmware, right?

**Comment by jbqubit** [comment]
I figure it would be nice to monitor RTM voltages/temperature when plugging it in for the first time. But not crucial since you've already done testing of the RTMs.

**Comment by gkasprow** [comment]
Yes, they got Saymas very recently so need some time to verify it.
RTM is also supported. Yes, leave it open.
