### ISSUE TITLE
MixMod schematic issues

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#388]
Thanks for producing the really nice Nanoga schematic. Basically looks really good! I've completed my review. Comments are below and in other issues under the [relevant milestone](https://github.com/m-labs/sinara/milestone/20). Please ask if anything is unclear.

**Questions**
- Why did you use the ADCLK944 instead of the two-output ADCLK925 (which has slightly better performance IIRC)? Is the 944 cheaper or something?
- Since we are not using the demodulator, we only need one LO signal, so could scrap the clock buffer. However, for higher frequencies, the LO power from Sayma may be quite attenuated. Do you think that in this case, it makes sense to keep the clock buffer, since it will work better with the weaker LO? Or, do you think the modulator can handle the weaker LO as well as the clock buffer?
-  Why generate the 3V3 from the 5V0, rather than directly from the 6V0?

**Misc issues**
- [ ] Let's make sure that we're using the cheapest substrate that will provide acceptable performance up 6GHz (the frequency limit of most components on this design).
- [ ] +-5V regulators must have diodes
- [ ] Is it worth putting inductors on the +-12V rails to remove high-frequency noise (these are generated by SMPSs on Sayma IIRC)? This is probably a good idea since there is no regulator on the supplies used for the InAmps. If we do this, we should also do this for Allaki.
- [ ] If we make this board a bit narrower, will that avoid some of the mechanical issues we've had with Allaki?

**Comment by hartytp** [comment]
Okay, sorry for the omission, but a big issue I missed in my review:

- The current demodulator arrangement won't work for us, since the BW of the ADC, demodulator etc is too low. Our RF frequency from the DAC will be up to 400MHz which is outside the bandwidth of these components.
- So, to fix this, the LO for the demodulator needs to be supplied by the RF output from the modulator. This can be done, for example, using a resistive splitter after the amplifier (we probably need some attenuation there anyway).
- This may allow us to scrap the LO fanout buffer. Or, you can keep it if you think it helps with signal integrity (what behaves better with a bad input clock? the buffer or the modulator?). If you think it will help, you could also add a clock buffer at the demodulator's LO input to square up the RF signal.
- The disadvantage of this arrangement is that the demodulator doesn't work when the DAC RF isn't on. But, I don't really see any way of getting around that (clever suggestions @dhslichter?)

**Comment by hartytp** [comment]
Sorry, ignore the above. That's not a nice way of using the demodulator.

Provisionally, my conclusion is that we should just scrap the demodulator entirely. If we need it, it should probably be on a separate PCB.

Let me have a think about this and confirm what I'd like to do soon.

**Comment by hartytp** [comment]
@gkasprow Okay, I've completed my review for this design (again!). See the top post on this issue for details.

Most of the changes involve removing components to simplify the design, so hopefully it's not too much work. Let me know if you have any questions. Otherwise, can you post the schematic once it's done so I can sign off on it.

Thanks!

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#5
