### ISSUE TITLE
Sayma upconverting AFE schematic review: cosmetic/documentation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#391]
- [ ] With apologies to @jordens let's drop the name Nanoga and just call this "MixMod". On the silk, please put "MixMod Upconverting AFE" applies to schematic and silk. Put the files in a directory "Altium/Sayma_AFE/MixMod".
- [ ] Add version number (v1.0) to schematic
- [ ] On ADC channel page, "Variant" not "Wariant" (this is wrong in Allaki as well)
- [ ] Text is upside down for C4, R40, R42, C63 (also wrong on Allaki)
- [ ] Should probably have a power budget on the schematic like the ones for the EEMs. This applies to Allaki as well.
- [ ] Remove annotation "input considerations and Variants ...”
- [ ] What are C45, R69, etc for? Can we scrap these? There are quite a few components on this PCB for matching, which I don't anticipate using, but which take up space. Would it be worth removing some of them?
- [ ] Make sure that all signals are zero-indexed

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#4
