### ISSUE TITLE
Sayma upconverting AFE schematic review: filters

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#392]
- [ ] There should be a 1:1 balun or choke between the DAC outputs and IQ modulator to improve common-mode rejection.
- [ ] Add a 0R resistor between the DAC outputs and the modulator inputs. This allows the DAC outputs to be AC coupled into the modulator if that's ever required (e.g. if we find that the DAC has bad low-frequency noise)
- [ ] Can we have low-pass (reconstruction) filter between the DAC outputs and the IQ modulator?
  - I'm assuming we'll use interpolation with a DAC clock frequency >= 2GHz. Max DAC (IQ) output frequency is 400MHz so the bulk of what we're trying to filter out will be at frequencies above 1.6GHz.
  - Pick whichever filter you want that will pass 400MHz but block above about 1.5GHz. I didn't find any MCL differential filters, so we could either build our own out of discrete passives or do something like use 2 x XLF-641M+ for each DAC (please double check that there isn't a more suitable part before using!). I don't mind whether you use the discrete filter or the MCL; do whichever is easier/cheaper/better (just make sure you annotate the schematic with the passband etc for the chosen filter).
- [ ] Do we need a filter between the mixer and amplifier? AFAICS, the only reason for this would be a high-pass filter to kill baseband leakage from the modulator (is that necessary?). If we do add this filter, pick either a MLC filter part or use passives (whichever is easier) but don't leave space for both! e.g. could be a high-pass that blocks 400MHz but passes above, say, 1GHz. If we use this filter, please add an annotation for this filter specifying corner frequency etc.

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#3
