### ISSUE TITLE
Sayma upconverting AFE schematic review: modulator

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#393]
-  [ ] I'd like the modulator to be enabled when the enable signal is not actively driven, so this pin should be pulled low, not high as in the current design. That way we don't have to actively drive this pin to make the board work.
- [ ] Modulator IQ inputs must be biased to +500mV by the DAC. If I understand correctly, the biasing resistors have been chosen so that with 20mA full-scale DAC current the common-mode voltage offset is 500mV and the swing is 1Vpp (+4dBm), while still providing a decent 100R differential termination to minimise reflections. Is that correct? This info should all be annotated on the schematic.
- [ ] Do we we need a bit of attenuation after the clock mux that supplies LO for the modulator? For lower LO values (below about 3GHz), the mux supplies 1.5Vpp differential signal = +8dBm. But, the modulator wants a max LO input power of +6dBm. Let's aim for the max LO power (i.e. power for frequencies <2GHz) to be a little below +6dBm after the balun
- [ ] Please add an annotation with the power out of the IQ modulator when the DAC is running at max amplitude. Do we need an attenuator between the modulator and the amplifier to avoid saturating the amplifier or other components when the DAC is running at max amplitude? Should we have an attenuator like this on Allaki as well?
- [ ] All RF signals from Sayma AMC should come through a balun or CMC to reduce cross-talk in the connectors. I and Q channels should be DC coupled into the modulator.

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#2
