### ISSUE TITLE
Sayma upconverting AFE schematic review: connectors

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#395]
- [ ] Let's remove RF_OUT1 SMA, so we just have a single output SMA, labelled "OUT" on the schematic + silk.
- [ ] Let's have 2 input connectors, both MMCX to match BaseMod AFE. Inputs should be labelled IN0 and IN1. Both inputs should have identical input paths (filter, InAmp, ADC driver, ADC). Inputs can be used for IQ signals from external demodulator.
- [ ] Input/output connector caps should be 2*1nF on each connector. (Why are there three caps on the input SMA?)

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#1
