### ISSUE TITLE
Sayma upconverting AFE schematic review: power detector

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#397]
- [ ] Let's scrap the power detector and all associated circuitry (attenuator etc). (I'd also suggest we consider doing this for the next revision of Allaki)!
- It takes up an annoyingly large amount of space on an already cramped PCB and adds extra cost and complexity and power dissipation.
- I don't think it's actually that useful because:
  - It is read out by the 24-bit ADC which is very slow, currently untested and doesn't have any drivers written for it.
  - In most cases, the dominant source of drift/power errors come from components external to Sayma, such as power amps etc
  - The thermal environment for this power detector isn't great, so the detector's stability won't be amazing.
  - Generally, it's probably better to use an external detector (e.g. an ADL5511) in a well controlled environment near the load and to read the detector out using the InAmp and the fast ADC.

For the reasons above, I'd argue that we should also scrap the detector on Allaki (which is extremely cramped and short on space) unless people **really** want it and intend to use it regularly.

**Comment by hartytp** [comment]
Note also that on the Allaki schematic R18 and R19 seem to be populated, as well as the power detector. Either these are actually DNP, in which case that should be clearly indicated on the schematic, or this is a mistake!

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#8
