### ISSUE TITLE
Sayma upconverting AFE schematic review: input configuration

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#398]
- [ ] We only need one input path to this board: SMA -> InAmp -> ADC driver amp.
- [ ] Please remove the solder jumpers for the input path (if there are no more solder jumpers on this board, please remove the solder jumper diagram as well!)
- [ ] Please remove the pads for input matching components (the BW on this input is <1MHz so we don't need to try to match out the connector parasitics!)
- [ ] Please remove the table of resistor values for the ADC driver
- [ ] Please set the ADC driver resistor values appropriately for the InAmp
- Note that we don't need a "fast" input path like the one on Allaki, which connects the input SMA directly to the ADC driver OpAmp. In future, we will probably use a slower ADC so this path will be removed from Allaki as well.

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#7
