### ISSUE TITLE
Sayma upconverting AFE schematic review: demodulator

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#399]
- [ ] Please remove the demodulator. It was a nice idea, but doesn't really work out four our use-cases:
  -  Demodulating using the same LO that's used for the modulator doesn't work because the IF we get is at the same frequency as the DAC's RF. This is too fast for the ADC and other components, and would require resource-intensive digital demodulation inside the FPGA (gateware which is not written yet!)
  - We can't use the RF output from the modulator to supply the demodulator LO because we pulse the DAC's output on/off and do pulse shaping etc. So if doesn't provide a good CW LO
  - Demodulation is probably best done on a separate board using a cheap DDS to provide the demodulator's LO. This could be a simple EEM.

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/MixMod#6
