### ISSUE TITLE
Sayma Front Panel

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#400]
- [ ] Sayma front panel should have 1 large cutout for each AFE, rather than having holes for SMAs. Each AFE then has its own front panel, which houses the connectors. This is a similar situation to FMCs.

Context:
- This gives users/AFE designers the ability to choose the connectors on their AFE according for their needs. e.g. low-frequency input connectors can be MMCX rather than SMA/SMP which resolves a mechanical issue with the current AFE design and reduces costs.
- With the current front-panel design (with individual SMA cutouts) it's hard to fit AFE mezzanines onto Sayma. Moving to larger cutouts for the AFE mezzanines should resolve this issue

Risks/cost/complexity:
- It might not fit together! However, it can be prototyped with cheap FR4 PCBs and laser-cut front panels to reduce this risk.
- Probably no more less risky or time consuming than any other way of resolving the current AFE mechanical issues.

**Comment by jbqubit** [comment]
I like this approach. It also permits pushing the choice of connector to the AFE level. https://github.com/m-labs/sinara/issues/7#issuecomment-348536026
