### ISSUE TITLE
Sayma cost

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#403]
@gkasprow when you have time, please can you post a breakdown of the main factors contributing to the cost of producing Sayma AMC/RTM. Would be good to know the cost of each item (cost of component, as well as cost of assembly) for a batch size of, say, 20 Sayma.

Once we have this info, we can make more informed decisions about which (if any) components to remove/change from Sayma for v2.0.

**Comment by dhslichter** [comment]
@gkasprow please bundle some costs together, e.g. RF connectors (currently SMPs) between RTM and mezzanines, or front panel connectors, should be bundled as a unit cost per Sayma.
