### ISSUE TITLE
Sayma Regulators

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#406]
- [ ] Consider removing some of the LDOs on Sayma RTM

Context
- We currently have 1 LDO per clock mux on Sayma RTM. THat's a bit crazy and increases costs/complexity.
- Motivation for having this number of regulators was to decouple ICs. However, that's necessary, since clock buffers only draw currents at the clock frequency. At this frequency LC filters work as well as having separate regulators
- In contrast, having separate LDOs for each DAC makes sense, since the DAC noise spectrum/current draw can be very broad-band.
- This will probably become unnecessary if/when we reduce the complexity of the clock network in Sayma RTM

**Comment by gkasprow** [comment]
@hartytp we have so many because they were used on the devkit and there were sufficient number of risks to mitigate. Some of them can be removed. Take into account that decoupling works well only beyond certain frequency, it also increases supply line impedance significantly. So if you need to keep the phase noise low, especially at low frequency offsets, it's better to keep these LDOs.

**Comment by hartytp** [comment]
Okay.

Out of all the Sayma v2.0 issues raised so far, this is probably the least important, so if you'd prefer we can keep the regulators. In any case, some of them will disappear once we simplify the clock distribution network, so will become less off an issue.

FWIW though, I still think that many of these regulators are unnecessary. I can see the argument for having the DACs on their own regulators, since they can draw quite a bit of current with a very broad spectrum. However, I don't see that having a separate regulator for every clock buffer is required. These only really draw current at the clock frequency (plus some fixed bias current, which is very low noise), so LC decoupling is absolutely fine. Clock buffers just don't draw large low-frequency noisy currents.

If we can time, we can always test this using the Sayma v1.0 prototypes and then we'll know for sure.

**Comment by marmeladapk** [comment]
I feel that this is no longer applicable:
- Clk distribution has separate LDOs for HMC830, ADF4356 and ADCLK948, which is fine by me,
- @hartytp said that DACs should (or at least can) their own regulators
- There are no other "duplicate" regulators and CLK distribution was vastly simplified
