### ISSUE TITLE
Clock mezzanine

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#407]
- [ ] Remove the clock mezzanine from Sayma RTM

Context:
- It makes sense to generate data converter (DAC/ADC) clocks locally (ie on each RTM/FMC) rather than distribute them down the RF backplane. This is because one can imagine using many different data converters in the same uTCA rack, each needing a different clock frequency. Muxing all these clocks would be a nightmare (if one even has enough lines on the BP to do it in the first place!). 
- In contrast, I can't think of any cases where it's useful/necessary to have more than a single LO per experiment. The LO generally sets the overall scaling for the frequencies that we're working at (e.g. 12GHz for Yb) and exact frequencies are created by upconversion. As a result, distributing LOs down the backplane seems like a much better idea than having each Sayma generate the same LO frequency locally. Note that the BP is specified to about the same frequency as the clock buffers we're using. Very high frequency LOs can be created by doubling on the AFE.
- Data converter clocks are generally less critical than LO in terms of noise and drift, since the RF is generally at a lower frequency. So, local generation is much more practical for converter clocks than for local oscillators. 
- So long as the HMC830 performance checks out and does not limit the DAC's overall performance, I would recommend removing the clock mezzanine option from Sayma for the above reasons. Let's just make sure that we leave open the option of providing each of a 100MHz reference and a LO both through the FP and through the BP. That only requires a single fanout/mux for the each of the 100MHz reference and the LO, which is nice and simple compared with the current situation.
- Under this proposal, the clock mezzanine would still be really useful as a high-quality PLL, for example for generating the LO. However, it doesn't need to be built into an AFE mezzanine form factor. My recommendation is to build it as a EuroCard, which can be used to supply the LO for either Sayma or Baikal.
- *better to delete it than to DNP it* because the clock mezzanine AFE currently takes up a lot of RTM FPGA lines! Freeing these up for other purposes (e.g. routing to the AMC FPGA or the AFE mezzanines) would be very useful. Also, note that if we DNP it, we have to keep room for it in the power budget.
- HMC830 phase noise is not expected to degrade the DAC's performance noticably, but this needs verification. cf @WeiDaZhang simulation: ![hmc830](https://user-images.githubusercontent.com/21218399/33504965-de536804-d6a6-11e7-9b15-3525f79b2af7.jpg)

To do: verify HMC830 noise/drift performance. cf #405

Risks:
- If the performance of the HMC830 checks out, this is essentially risk free. We just need to click DNP/delete a few times. For LO generation, it's nice to decouple the PLL board from the restrictive AFE mezzanine form-factor. It's also nice to have the option of putting the PLL in a better thermal environment than Sayma RTM.

**Comment by gkasprow** [comment]
removed
