### ISSUE TITLE
BaseMod input path

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#409]
- [ ]  BaseMod input path should be a direct copy of Sampler.
- [ ]  AFAICT, once we do this we can remove the -5V regulator.
- [ ] If ADC on BaseMod is faster than 1 MSPS then change RC filter to increase BW appropriately.
- [ ] Remove the "fast" input path where the SMA connects directly to the ADC driver OpAmp. This is no longer useful in the BaseMod design, as there won't be a fast ADC! This is easy to add back later if needed (i.e. if the JSED ADC is ever populated and supported!), but will simplify the routing/schematic for BaseMod.
  - [ ] This means removing the solder jumpers. We can also remove the matching pads at the input (this signal BW is about 1MHz so we don't need to worry about matching connector parasitics out). 

Risks:
- Low, we can copy an existing, well-tested design taken from Sampler.

**Comment by gkasprow** [comment]
The capacitors should be not far from the ADC, trace inductance can add some error. But they also shape the bandwidth so it may limit some use cases.

**Comment by hartytp** [comment]
> But they also shape the bandwidth so it may limit some use cases.

True. But in this case, the capacitors are big enough and the frequency is low enough that I don't think it will be a problem.

**Comment by hartytp** [comment]
I was thinking of the following layout for the ADC inputs on Sayma:
- 25R resistor
- Protection diodes (to +5V and GND)
- 25R resistor
- Capacitors

My reasoning is:
- I don't think it's going to be easy to sort the power sequencing out properly for these ADCs, so probably better to assume that the wrong voltages will be applied to the ADC inputs and make the whole thing robust with diodes.
- The idea of splitting the resistors is that the first resistor limits the current through the diodes, while the second resistor helps to ensure that the diodes turn on before the diodes in the ADC (what do you think about this approach).

Since there is no resistor on the AFE, the OpAmps will see the capacitive load presented by the traces and connectors. Do you think this will be enough to cause ringing? If so, should we put something like 20R on the AFE right by the OpAmp outputs?

**Comment by gkasprow** [comment]
@hartytp this approach should work.

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/BaseMod#3
