### ISSUE TITLE
DNP Sayma RTM JSD204 ADC

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#413]
- [x] DNP JESD204 ADC on Sayma RTM, as well as all associated components (regulators etc). Do not remove from schematic/PCB, so that users can populate them if they desire.
- [x] If easily possible, remove the JSESD ADC pages from the schematic PDF uploaded to the release (makes it shorter and easier to read).

Context:
- The JSED ADC has numerous disadvantages, such as power consumption, cost ($1k per Sayma!!!), complexity (not easy for users to hack, no existing JESD Rx MiSoc core), high latency, complexity (not properly tested yet).
- The main use-case for an ADC on Sayma is feedback loops with a few hundred kHz of bandwidth for laser intensity stabilisation etc. Because of the high JESD latency, the cheap LVDS ADC gives the same loop bandwidth as the JSED ADC, but without the drawbacks
- The Sayma JSED ADC isn't well-suited to downconversion applications, since one generally wants an ADC with the same RF bandwidth as the DAC. Using a 125MSPS ADC with a 2.4GHz DAC generally requires multi-stage down-conversion with external DDSs. Sayma is also not well-suited to applications like PDH locks, since it's too expensive and not optimised for the job; this can be done better by a cheap EEM. Applications like fast digitisation without feedback can be done equally well by an ADC not on Sayma RTM, e.g. use an existing (well-tested) FMC ADC.
- Can benefit from the design work done on Sampler to use a well-tested ADC, with an existing ARTIQ driver. This significantly reduces the risks involved. Moreover, this should make porting the NU-servo to Sayma much easier/cheaper.
- Potential concern is that the LVDS ADC does not allow scrambling. However, proper layout should prevent this from being an issue. Note that putting the ADC on the AFE mezzanine minimises risk since the mezzanine can always be redesigned cheaply.

**Comment by gkasprow** [comment]
Let's get rid of ADCs. We don't have them characterised. Guys at Creotech did some code to do basic tests but have some issues with synchronisation. So if there are some bugs, they will propagate. If someone wants to have 125MS/s ADCs, can use low cost AFC or AFCK board with FMC ADC boards. There are several open source and proprietary ones available. Let's use space to attach better cooling for DACs. 
If someone wants fast ADCs, we will have RFSOC solution in compatible form factor.

**Comment by gkasprow** [comment]
We can also route Rx JESD204B lanes to the analogue mezzanines if someone wants to play with fast ADCs on them.

**Comment by dhslichter** [comment]
I say strip the ADCs and the Rx JESD204B.  Just one more thing that needs testing, could go wrong, etc.

**Comment by hartytp** [comment]
> Let's get rid of ADCs. We don't have them characterised. Guys at Creotech did some code to do basic tests but have some issues with synchronisation. So if there are some bugs, they will propagate. If someone wants to have 125MS/s ADCs, can use low cost AFC or AFCK board with FMC ADC boards. There are several open source and proprietary ones available. Let's use space to attach better cooling for DACs.


Yes, let's do that.

> We can also route Rx JESD204B lanes to the analogue mezzanines if someone wants to play with fast ADCs on them.

I'm not bothered about this. I wouldn't bother with this. I don't see anyone putting a fast JESD ADC on the AFE mezzanines. Routing multi-gigabit lanes from the AMC FPGA to the AFE mezzanine with acceptable SI seems like a lot of work.

**Comment by gkasprow** [comment]
I removed the ADCs. Optionally one can install such ADC on mezzanine, together with clock distribution IC. JESD204 lanes are shared with LVDS ones and can be routed by changing capacitor assignment.
