### ISSUE TITLE
Clocker v1 errata and tests

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/sinara#421]
Clocker v1 arrived.
There are some minor issues:
- [ ] Use the 712RA barrel connector (not the long barrel L712RA). Same footprint. Just shorter barrel.
- [x] voltage setting resistor should be 33k instead of 3.3k
- [x] front panel SMA assignment is wrong - clock input is on bottom, not top. It was in initial project and changes were not transferred to the panel design.
- [ ] insulating washers are bigger than in documentation. The SMA port description must be shifted away by 1mm
- [ ] SMA connector mechanical models are different than actual connectors. Actual ones do not have a ring around the SMA thread. So I had to install a washer to give a support for insulating washer
- [ ] move new supply connector 0.75mm towards the panel
- [x] add insulating washers to BOM
- [ ] consider adding an LC filter or ferrite bead between the SMPS and LDO. Maybe add a tantalum cap to damp any LC ringing? Use same inductor that is already used on the SMPS in combination with a large tantalum cap.
- [ ] Populate MMCX input.
- [ ] Silk + schematic + panel should be "v1.x" not "rev1.x"

Otherwise it works fine.
Today I will ship it to @hartytp 

![clocker](https://user-images.githubusercontent.com/4325054/33881073-f703cc50-df33-11e7-8b00-df07dd8b6f49.jpg)

**Comment by hartytp** [comment]
Great, thanks!

**Comment by jbqubit** [comment]
Looks great!

**Comment by hartytp** [comment]
Had a look at clocker today. The error on the FP threw me for a while other than that, it looks good...

Source for all measurements is a Wenzel 100MHz oscillator (+13dBm) driving clocker directly via the FP SMA.

**Comment by hartytp** [comment]
Rise time is something like a few hundred ps ignoring the reflections. The ADCLK itself should provide more like 100ps, but once the balun and the scope BW (4GHz) are taken into account, this is roughly what one expects.

Pk to pk signal is about 800mV. Expect 16.Vpp out of the ADCLK, that's 1.1Vpp into 50R, and 900mV once the 2dB (ish) balun loss at 100MHz is taken into account.

SI looks generally good on the scope. So this all checks out...
![20180201_141859](https://user-images.githubusercontent.com/21218399/35683158-026f8cce-075b-11e8-8069-12fb725ed677.jpg)
![20180201_141844](https://user-images.githubusercontent.com/21218399/35683160-03fada26-075b-11e8-9c69-034e55862ffc.jpg)

**Comment by hartytp** [comment]
Phase noise looks excellent (plots to follow later).
- noise floor at about -145dBc/Hz
  - NB this is not expected to follow the 20*log(f) scaling with the frequency of the carrier.
  - limit to white noise is probably the fact that I'm doing this at 10MHz. dV/dt is: 2xpixAxf= 2xpix(sqrt(2)x1.4V)x100MHz=1V/ns. Looking at figure 12 of the datasheet, we're definitely still in the regime where the jitter is limited by the input slew rate, so this makes sense.

**Comment by hartytp** [comment]
I did see a few spurs, particularly on the AM spectrum, which look like they come from the SMPS. Probably worth adding an LC filter (or ferrite) between the SMPS and LDO. If we do that, make sure to add a tantalum cap or something to prevent ringing in the LC filter.

**Comment by hartytp** [comment]
Anyway, great work @gkasprow on another design that worked more or less perfectly on the first attempt! It's a very low priority compared with Sayma/Booster, but at some point I'd like to order some more of these with the bug fixes applied.

**Comment by gkasprow** [comment]
I have a few pieces still in my lab. I will test them in a few days.

**Comment by hartytp** [comment]
@gkasprow There are no more tests that I want to see done; as far as I'm concerned this board works and nothing else is needed.

I'd prefer to buy v1.1 boards with the fixes applied (e.g. a new front panel!).

**Comment by gkasprow** [comment]
new front panel is already attached to all shipped boards. We can ship you correct one.
All the fixes are already applied to existing boards, so the only difference would be this ferrite bead.
You wanted 4 clocker prototypes, @jbqubit  wanted 2, we did 10, so there are still 4 free ...
Actually, I can mount these ferrite beads on existing 4 pcs so they won't differ from v1.1.

**Comment by hartytp** [comment]
@gkasprow okay, np. If you apply the fixes above then that's fine by me.

**Comment by gkasprow** [comment]
Here is a fix:
100R/1A ferrite bead + 6.8uF tantalium cap
![2018-02-01 16 26 07](https://user-images.githubusercontent.com/4325054/35687322-b141f3d2-076e-11e8-9a2e-feebd73eab1e.jpg)

**Comment by hartytp** [comment]
> 100R/1A ferrite bead + 6.8uF tantalium cap

What P/N?

**Comment by gkasprow** [comment]
well, I took one from a drawer. It is 100R@100MHz, 150mOhm, 1A ferrite bead. i.e. [this one](http://pl.farnell.com/tdk/mpz1608d101bt/ferrite-bead-100r-1a-0603/dp/2800770)
6.8uF/10V SMDA, ESR is roughly 3R, one can use [this](http://pl.farnell.com/avx/taja685k010rnj/cap-tant-6-8uf-10v-case-a/dp/2283842?st=6.8uF%20SMDA%2010V)

**Comment by gkasprow** [comment]
I modified and tested remaining boards

**Comment by hartytp** [comment]
That won't do much for frequencies <=100kHz will it? The cap ESR is comparable to the bead's impedance isn't it? At that frequency, the FB is just a small inductor IIRC.

**Comment by gkasprow** [comment]
The tantalium cap is just to lower the Q of the LC circuit. There is 10uF cap at the LDO input.

**Comment by gkasprow** [comment]
edit 4.7uF ceramic cap

**Comment by hartytp** [comment]
Still not convinced that's enough. At 100kHz the 4.7uF cap is about 0.3Ohm. Hard to tell from the FB datasheet, but the impedance at 100kHz looks <1Ohm there as well.

**Comment by gkasprow** [comment]
what we want to achieve is to improve LDO PSRR at higher frequency. Isn't LDO performing good enough at 100kHz? I can place small inductor there, let's say 10uH

**Comment by hartytp** [comment]
Most of the noise I saw on the output was below 1MHz. So, yes, an inductor and tantalum would probably be the best solution. Let's use the same inductor we already have on the SMSP to avoid introducing an additional BOM line.

**Comment by gkasprow** [comment]
I used 6.8uH 2.2A inductor I have in lab:
![Uploading 2018-02-01 17.35.19.jpg…]()

**Comment by hartytp** [comment]
Nice, that should do it.

**Comment by hartytp** [comment]
Tried increasing the SMSPs output voltage to 4V to improve the PSRR of the LDO. Didn't seem to make any difference...

**Comment by jbqubit** [comment]
@hartytp Will be interested in seeing your phase noise plot. Please also post that PN for your reference oscillator (or give part number). Do you have a scope that generates eye diagrams?

**Comment by hartytp** [comment]
Plots look essentially the same as the ones I posted in the issue about the LTC6957 (or whatever the PN is); they're basically what the ADCLK948 datasheet gives. But, yes, I'll post them when I have time.

Will post the oscillator PN. FWIW, we always measure and plot the phase noise of the reference at the same time. That shows the overall noise floor of the measurement.

Eye diagrams aren't useful in this context and any measurement would just be the noise floor of the scope. The phase noise spectrum has everything you need.

**Comment by hartytp** [comment]
@gkasprow Shall we make the tantalum after the inductor 100uF (assuming that's cheap and readily available in an appropriate package) to really kill the SMPS crud in the 10kHz regime?

**Comment by hartytp** [comment]
> It would be interesting to get a number for the isolation of the clock mux. With one or both inputs being sinusoidal.

**Comment by jordens** [comment]
What is the "datasheet value"? It's unclear (to me at least) what that 90 fs rms value means. I'd expect that to depend dramatically on at least signal slew rate.
ACK the rest. I.e. 5 dBm output.
Just out of curiosity: how much power is in the even harmonics?

**Comment by hartytp** [comment]
> What is the "datasheet value"? It's unclear (to me at least) what that 90 fs rms value means. I'd expect that to depend dramatically on at least signal slew rate.

ACK, I thought it was better specified than that, but I may be remembering a different datasheet. Will measure once my cables arrive.

> Just out of curiosity: how much power is in the even harmonics?

Will do.

**Comment by jbqubit** [comment]
As a reference for a clock distribution amp see [SDI HPDA-100RM](http://www.spectradynamics.com/products/hpda-100rm-high-performance-distribution-amplifier-80-20mhz/).

**Comment by hartytp** [comment]
NB about that kind of thing:
- They don't perform sine-square conversion, which is usually where a lot of the noise comes from for lower frequency references. i.e. if you clock a PLL/DDS off the output from that at 100MHz then don't expect the performance to be as good as the datasheet value.
- IIRC (conversations with the manufacturer) the propagation-delay temp co is about 1ps/K compared with 0.1ps/K for the ADCLK, so AFAICT (not characterised carefully) if you really care about phase stability the ADCLK is the way to go.
- AFAICT, the noise from the ADCLK is low enough to not be a limit in any of the applications we have in mind (see the phase noise models Weida's posted).

That aside, yes, those are very nice buffer amps...

**Comment by gkasprow** [comment]
@hartytp I just realised that we have already good LC filter after the buck converter. The converter has embedded inductor. So at its output there is already 6.8hD inductor + 22uF tantalium + 22uF ceramic and then LDO.
I had some brain fade and didn't realize this :D

**Comment by hartytp** [comment]
@gkasprow ack. In that case, we can leave it as is.

Before I forget, can you send me another two boards with the other fixes applied, please? (Very low priority).

**Comment by gkasprow** [comment]
I handled them to Technosysem some time ago...

**Comment by hartytp** [comment]
Okay, so I order from them? Will they apply the fixes above?

**Comment by gkasprow** [comment]
yes

**Comment by marmeladapk** [comment]
_Migrated to sinara-hw/Clocker#2_
