### ISSUE TITLE
Sayma/BaseMod v1: use lower insertion force SMPs

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#438]
Considerable force required to insert/remove BaseMod AFE into Sayma_RTM #386. This will be addressed in Sayma 2.0. In the meanwhile when stuffing additional BaseMod AFE populate with Smooth Bore or Catcher’s Mit (SB and CM) to reduce [force](https://github.com/m-labs/sinara/issues/368#issuecomment-348289952) at one interface.

**Comment by gkasprow** [comment]
Before we stuff next batch, it would be good to characterise existing ones...
