### ISSUE TITLE
Sayma_AMC: interacting with ARTIQ dynamically

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#445]
Due to ongoing problems [getting RGMII to work on Sayma_AMC](https://github.com/m-labs/artiq/issues/854) there is currently no operable path for [running ARTIQ dynamically](https://github.com/m-labs/artiq/issues/854). Options as of 12/14 are summarized [here](https://github.com/m-labs/artiq/issues/854#issuecomment-351793482). This Issue is a continuation of https://github.com/m-labs/artiq/issues/854 for tracking this broader problem.

**Comment by hartytp** [comment]
No hardware issue here, closing
