### ISSUE TITLE
Booster RF PA panel text

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#451]
@gkasprow For the RF PA front/back panels:

c.f. the style guide on https://github.com/m-labs/sinara/wiki/EEM 

**Front panel**
- [x] I don't think any particular logo is necessary. I don't have a specific logo in mind for this product (although, feel free to suggest one). I don't think it's appropriate to put an ARTIQ logo on it, since this product isn't really an ARTIQ device (although, if there were a separate Sinara-specific logo, we could consider adding that). Feel free to add the WUT logo, and any OpenHardware logos you think are appropriate. Just make sure they look nice when engraved (and aren't overly complex/expensive to machine).
- [x] "*Booster* RF Power Amplifier v1.0" Feel free use any way you want to visual separate the name "Booster" from the description "RF Power Amplifier" e.g. use a long dash instead of italics. 
- [x] Label input and outputs (zero-index channels). Maybe put a box (rounded corners) for each channel, enclosing the two SMAs
- [x] Label ethernet ("Eth", "Ethernet", etc) and the USB ("Firmware"/"Updates" or something)
- [x] Label the two push buttons according to their function. Maybe something like "Reset" or "Clear protection" for the protection button. What does the other one do again?
- [x] Label channel numbers on the LHS of the row of LEDS. 
- [x] Label the three rows of LEDs: Green something like "RF On"/"Ok" or something; red "Error" or maybe "Over temp/current"; and yellow "Overload" or "Standby" or something. Or something like that. Ideally, let's try to keep all text horizontal. Maybe use 45deg line to connect the text to the LEDs or whatever you thinks looks good/clear visually.
- ~Maybe add a "Ventilation, DO NOT BLOCK" label by the vents.~
- Anything else?

**Rear pannel**
- [x] Label fuse ratings
- [x] Label power connector with input voltage range, frequency range and power rating (something like ("120V - 240V, 50Hz/60Hz, ?VI")
- [ ] Label all safety ground bolts ("Safety ground, DO NOT TAMPER", maybe add a PE symbol?)
- ~Label ventilation/do not block~
- Anything else?

With all these things, feel free to overrule the suggestions above and do whatever you think is most appropriate/standard for this kind of equipment. Also, feel free to adapt these suggestions to the space available.

**Comment by dhslichter** [comment]
@hartytp edited to fix bandwidth spec above.

I think it would be nice to say "Booster RF Power Amplifier" in engraved text, and then have a sticker underneath that has the specs of the amplifier inside (for example: HPA4501, 50-400 MHz, 42 dB gain, 37.5 dBm Psat).  This enables two things:
1. It gives all the relevant information to someone trying to hook this up in the lab, without their needing to hunt down the datasheet.
2. Since it's a sticker, it can be peeled/replaced if one makes a variant of the amplifier inside with different specs (since after all this is designed to be modular).  

I would lean against putting frequencies and output powers in engraved text on the front panel.

**Comment by hartytp** [comment]
> 42 dB gain, 37.5 dBm Psat

I wouldn't be that specific, since the gain flatness is only a bit better than +-2dB. We can go for something like "40MHz-500MHz, 40dB gain, 5W" if you really want all that info on there.

> I think it would be nice to say "Booster RF Power Amplifier" in engraved text, and then have a sticker underneath that has the specs of the amplifier inside (for example: HPA4501, 50-400 MHz, 42 dB gain, 37.5 dBm Psat).

hmmm. I'm not so keen on that. Stickers have a habit of coming off or rubbing off. Plus, if they're not stuck on carefully they look wonky and bad. Having everything engraved looks much nicer and is much more durable.

In general, I'd prefer to put less info on the front panel but have it all engraved properly than put loads of information on stickers (users can always do that themselves if they want).

Do we think that people are likely to produce other amplifier designs for booster any time in the near future? Remember that the physical format and power dissipation are quite limited due to the high channel count (e.g. not enough current to put MCL high-linearity amplifiers in there).

And, if people do contribute new amplifier designs then they might want to add stickers on a per-channel basis, rather than a per-module basis.

Finally, I'm not sure how useful info like gain, saturation power etc are on the front panel, since the tolerances/flatness are (by design) not that high for this amplifier. I don't want users to see 40dB of gain on the front panel and then be surprised when they measure 38.2dB at some frequency.

So, maybe it's better to just remove all frequency/power/gain info from the front panel. Users can add stickers as desired.

**Comment by dhslichter** [comment]
> So, maybe it's better to just remove all frequency/power/gain info from the front panel. Users can add stickers as desired.

I would do this -- just a name for the system ought to suffice.  And then users can add stickers featuring whatever specs they find most compelling.  It seems to me that the physical form factor is nice and could be quite general, the boards inside are not highly complex so one could manufacture variants for other applications if so desired.

**Comment by dtcallcock** [comment]
The absolute max input power would be nice to have right next to the SMA connector.  This is usually the one thing people need to know before following the 'have a bash first and then read the datasheet if it doesn't do what you expect' approach favoured by grad students and PIs the world over.

**Comment by hartytp** [comment]
You mean absolute max without damage? That's pretty high in this design IIRC, since the first components are a 20dB coupler + RF switch, which cuts off the input once it exceeds a (user programmable threshold). i.e. you shouldn't be able to break this amp with a standard synth + preamp setup. More useful might be the labelling the input power that saturates the output (which is only defined to a couple of dB due to the gain flatness).

Anyway, I'm fine to include that kind of info on the FP if people really want it. But,  I would like any info we include to be properly engraved rather than using a sticker. IMHO, the chance of anyone swapping out one of these amplifier modules for one with a different specification is pretty low, so I'm fine to add this to the FP if people really want it.

**Comment by dtcallcock** [comment]
Yeah, if you'd have to put a Watt or something in to break it then I agree that it's not that important.

**Comment by hartytp** [comment]
Someone with the schematics would have to check what the actual figure is, but IIRC the damage threshold is >100mW. That's high enough to avoid damage from the vast majority of sources/preamps in the lab. In principle if people think that's not enough then we can probably bulk it up with some protection diodes.

**Comment by hartytp** [comment]
Currently there are two switches on the front panel. I'd like to clarify their functionality:
- 1 should be an interlock reset switch. Front panel label something like "Interlock reset" or "Protection clear". This clears the interlock status of all channels
- The second switch is optional IMHO and can be removed if that helps. The best use I can think for it is a "Standby" switch that powers down as much circuitry as possible (ideally also disabling the fans). Pressing it once moves the device to standby, pressing it again moves it to active. This is a kind of soft power off switch which is potentially nice since the main power switch at the back will be inaccessible when this is mounted in a rack.
- When the device is first powered on, it should begin with all channels active (i.e. not in standby and no interlocks activated). We should be able to rely on the interlocks to trip if there is a problem e.g. due to no load connected.
- LEDs are then:
  - RED: over temperature
  - Green: all okay
  - Yellow: forwards/reverse power interlock tripped
  - None: standby

How does that sound?

**Comment by gkasprow** [comment]
@hartytp initial panel design
![obraz](https://user-images.githubusercontent.com/4325054/37427414-b172fed4-27c9-11e8-8413-363b93e8bf90.png)

**Comment by gkasprow** [comment]
And the rear panel
![obraz](https://user-images.githubusercontent.com/4325054/37427950-14b73eb4-27cb-11e8-806e-5071054ce534.png)

**Comment by dhslichter** [comment]
Looks nice @gkasprow!  One item: the LED legend that says "OVERLOAD" looks to me like it might actually be a typo and say "OVERLDAD", but this could just be an artifact of the image resolution.

**Comment by hartytp** [comment]
Thanks @gkasprow! That looks really nice. Comments:

Front panel:
- Let's remove the "10/100" label on ethernet

Rear panel:
- Please can you label the required fuse by the IEC
- Add a PE symbol/"safety ground DO NOT TAMPER" by the grounding if you think it's required

Otherwise, no comments (other than I think this is going to look really nice!)

**Comment by gkasprow** [comment]
@hartytp the fuse is placed in the SMPS module only. The rear panel has only IEC plug with mains switch.
Failing fuse in SMPS usually means serious problem so it's better to not expose it to the user.

**Comment by gkasprow** [comment]
you mean this logo?
![obraz](https://user-images.githubusercontent.com/4325054/37434725-e5dd98f2-27e0-11e8-8f41-dbeee8ce2af8.png)

**Comment by hartytp** [comment]
@gkasprow 

> the fuse is placed in the SMPS module only. The rear panel has only IEC socket with mains switch.
Failing fuse in SMPS usually means serious problem so it's better to not expose it to the user.

Okay, if there is no fuse in the IEC socket then no label is required!

> you mean this logo?

Yes, that one. If there is a sensible place to put that near an important safety ground bolt that must not be removed, then please add it.

**Comment by hartytp** [comment]
On second thoughts, it's probably not worth labeling the vents with "do not block".

**Comment by dhslichter** [comment]
> On second thoughts, it's probably not worth labeling the vents with "do not block".

We could label the vents as "vent (air)", and put a label on the front panel that says "front panel".  I also think it would be useful to have something that says "please don't eat the daisies". ;)

**Comment by gkasprow** [comment]
And on rear panel we could place a note "remember to connect the power cord" ;)

**Comment by hartytp** [comment]
All looks good to me.
