### ISSUE TITLE
baseMod documentation

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#491]
baseMod is the-board-formerly-known-as-Allaki. 

### AFE Interface 

Discuss broader AFE interface concept. baseMod is one manifestation of an analog front end. 

### baseMod details
[Wiki](https://github.com/m-labs/sinara/wiki/SaymaAFE) gives a head start. 
- [ ] discussion of use case (frequency range, output impedance, etc)
- [ ] AFE interface (photo, names of pins) 
- [ ] power dissipated

### test results
- [ ] output chain phase noise
- [ ] switch isolation 
- [ ] attenuator isolation
- [ ] power supply rejection
- [ ] AM noise
- [ ] switch settling time
- [ ] attenuator settling time
- frequency-dependent plots (10MHz - 4GHz) 
    - [ ] output chain S parameters vs frequency
    - [ ] cross-talk vs frequency
    - [ ] IIP3 vs power and frequency (2D)

**Comment by jbqubit** [comment]
@filipswit can @sbouhabib help you with this section of documentation?

**Comment by filipswit** [comment]
Yes sure, that would be great.

**Comment by jbqubit** [comment]
@sbouhabib @gkasprow @filipswit any word on this?

**Comment by gkasprow** [comment]
This issue was moved to sinara-hw/BaseMod#1
