### ISSUE TITLE
Booster: Power supply issues

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#493]
See https://github.com/m-labs/sinara/issues/453#issuecomment-356691192 and https://github.com/m-labs/sinara/issues/453#issuecomment-356665396

**Comment by hartytp** [comment]
@gkasprow what's the plan for fixing theae issues in the next version?

**Comment by gkasprow** [comment]
We will fix them in this version.
I've ordered new, resonant SMPS. Have it in lab and needs testing.

**Comment by hartytp** [comment]
Great thanks. Can you fit that before you send us the amp back for further testing?

**Comment by gkasprow** [comment]
sure.

**Comment by hartytp** [comment]
Seems solved.
