### ISSUE TITLE
XADC reference

### ISSUE THREAD

**Issue by jordens** [sinara-hw/sinara#495]
* AMC: make C221 0R
* RTM: short VREFN and VREFP to GND, DNP C546

This enables the internal reference, power supply monitoring, die temperature measuremnet, and the overtemperature shutdown. Currently the RTM FPGA die is around 72 C when in use.

**Comment by hartytp** [comment]
That's quite hot. Was that measured with a fan or without?

**Comment by jordens** [comment]
Not really that hot. Kasli is the same without forced cooling.
It's Sayma-1 in HK, I don't know what the cooling situation is. @sbourdeauducq ?
