### ISSUE TITLE
DIO SMA 1.2

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/sinara#503]
- [ ] reverse DIP switch channels to match front panel channel assignment

**Comment by jordens** [comment]
The bottom SMA (channel 7) interferes with the handle. To use it that channel, the handle needs to be removed.

**Comment by gkasprow** [comment]
hm, I connected the SMA a few times and didn't notice that. Can you take a pic ?

**Comment by jordens** [comment]
Will do.

**Comment by jordens** [comment]
![img_20180322_201146](https://user-images.githubusercontent.com/1338946/37792960-9697921a-2e0d-11e8-80c9-804e746b3e15.jpg)

**Comment by gkasprow** [comment]
maybe on my board the SMA connector was assembled at slightly different angle or I have smaller SMA nut :)

**Comment by gkasprow** [comment]
@jordens do you observe this issue on all boards you have?
Maybe some cut-out in the handle would do the job? Not very elegant but if we make the connectors placed denser, we limit access space to them.

**Comment by jordens** [comment]
Yeah. I can wiggle it and file it off. It's on two out of three and the connector where the connector is at a slight angle. Could also be viewed as a QC issue.
8 SMA on 4 HP is too dense IMHO (but that's old news).

**Comment by marmeladapk** [comment]
_Migrated to sinara-hw/DIO_SMA#1_
