### ISSUE TITLE
Urukul v1.1 erata

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#504]
- ~Add extra LC filtering on sensitive analog power supplies.~
- [x] Replace loop filter passives with optimised values (AD9910 only):
  - C112 - DNP
  - R90 - 3.3k
  - R92 - 0Ohm
  - C99 - 68pF
  - C72 - DNP
- [x] Connect IC7 p 10 to P5V0, it was fixed in two other regulators but not in the IC7.

**Comment by gkasprow** [comment]
there already LC filters at the output of the SMPS.
There is 1.5uH + 47uF ceramic and 22uF tantalium. I can add yet another one just at the LDO.

**Comment by hartytp** [comment]
Aren't those inductors just the inductors required in the SMPS? Elsewhere, we've added a second inductor to help further reduce the ripple.

**Comment by gkasprow** [comment]
no, I used low EMI DC/DC converter with integrated inductors. These are low pass filters.

**Comment by hartytp** [comment]
Aaah, I missed that, sorry!

Okay, leave it as is. The noise is already good enough.

**Comment by gkasprow** [comment]
they are placed close to the SMPS to limit noise propagation. But the inductors may still pickup some noise from SMPS. We can add some inductor  on existing Urukul close to the LDO to check if this helps.

**Comment by hartytp** [comment]
Up to you Greg. The current situation is probably fine, but if the inductors are cheap and there is space for them then feel free to add them. In any case, basedon the data we have, this is a low priority.

**Comment by hartytp** [comment]
@WeiDaZhang has finished looking at the Urukul AD9910 loop filters. Turns out that the reason that the performance didn't match the simulations is that there is 1k resistor and 1.1pF capacitor on-chip, which was lowering the phase margin. These aren't mentioned in the datasheet, but are taken into account in the PLL design spreadsheet ADI provide.

Optimised loop filter components for the AD9910 variant of Urukul are:
C112 - DNP
R90 - 3.3k
R92 - 0Ohm
C99 - 68pF
C72 - DNP

@gkasprow Where are we with the Urukul manufacturing process? Have the boards been populated yet? If not, can we sneak this change into v1.1? If that's a problem, let's include this into v1.2.

**Comment by hartytp** [comment]
Measured PM and AM spectra using that loop filter...

[Urukul Phase Noise and Amplitude Modulation of 4dBm Output with Wenzel Referenced.pdf](https://github.com/m-labs/sinara/files/1733099/Urukul.Phase.Noise.and.Amplitude.Modulation.of.4dBm.Output.with.Wenzel.Referenced.pdf)

**Comment by gkasprow** [comment]
@hartytp the Urukul boards are already assembled and are waiting for tests.

**Comment by hartytp** [comment]
No problem, let's make this change next time we print a fresh batch of PCBs.

**Comment by gkasprow** [comment]
@hartytp did you test these values with hardware?

**Comment by hartytp** [comment]
@gkasprow yes, see the plot I posted. That was a measurement @WeiDaZhang made on one of our Urukul v1.0 boards using the new loop filter.

**Comment by gkasprow** [comment]
OK, so let's make new issue for Kasli 1.3

**Comment by hartytp** [comment]
@gkasprow pointed out in an email to me that the SMPS used in Urukul actually has integrated inductors, so the external inductors on the schematic are already a second stage of filtering. As there are no obvious performance issues in the current design related to SMPS spurs on the power lines, there is no good reason to change the design and add more inductors. So, I've removed that from the ToDo list at the top of this issue.

**Comment by hartytp** [comment]
@gkasprow once the current batch of Urukul is sold, can we make sure that the next batch produced is 
3,  including these changes? Thanks!

**Comment by gkasprow** [comment]
Sure.
