### ISSUE TITLE
Shuttler DAC parallel LTC2000 connection 

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/sinara#511]
I'm leaving results for future discussion.

As @gkasprow mentioned in #253 I made simulations for different FPGA output standards to check if it is possible to connect parallel LTC2000 (with internal LVDS termination) working with 150 MHz clock. 

First configuration was 4 DAC to 1 IO bank of Artix-7. Only BLVDS standard meets the requirement of input voltage range (min +/- 200 mV). With 3 DAC we can use also SSTL18.

![schemat3](https://user-images.githubusercontent.com/30114557/36147883-3e6b435e-10ba-11e8-81a9-7f1377ff1aa7.png)
Example of schematic with 3 DAC

![blvds](https://user-images.githubusercontent.com/30114557/36147899-4df3c3f0-10ba-11e8-90b9-390c7f3f82d9.png)
BLVDS simulation. Bit rate 600 Mbps.

![sstl18_ii_s](https://user-images.githubusercontent.com/30114557/36147930-7099cc92-10ba-11e8-8f89-2b4057f1a5ca.png)
SSTL18 simulation. Bit rate 450 Mbps

**Comment by hartytp** [comment]
This is very cool work, but it's covered by #253
