### ISSUE TITLE
Sayma PCB physical info

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#512]
@filipswit Please add some more information on the PCBs themselves. When placing institutional orders for Sinara boards its often necessary to get competitive quotes -- I just recently did this for Sayma v1.0. It helps to know about physical aspects of the boards for this as well as debugging the hardware. 
- [x] what are the copper layers? See [here](https://github.com/m-labs/sinara/issues/115#issuecomment-266078521).
- [x] What materials were used? PCB material, copper weight

**Comment by gkasprow** [comment]
Since some time all this info is automatically included in the output documentation as a stack-up report
