### ISSUE TITLE
Sayma_AMC heatsink detached during shipping

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#535]
Heat sink attachment failed during shipping from WUT to UMD. 

![image](https://user-images.githubusercontent.com/20543958/37986240-f0a0ef5e-31c8-11e8-829e-988645a2acc5.png)

![image](https://user-images.githubusercontent.com/20543958/37986273-083252c0-31c9-11e8-8354-1ba194ced4bc.png)

**Comment by hartytp** [comment]
Ouch! That must have taken quite a bang!

**Comment by gkasprow** [comment]
Oh, it menas the board survived a lot.
After you re-attach, make sure the brown plastic things are plugged deeply. They will secure the latches.
It's quite possible they were not secured.

**Comment by hartytp** [comment]
Joe, what's the action item here? Can we close this issue, or does something need to be done?

**Comment by jbqubit** [comment]
@gkasprow Please close after brining to attention of technosystem or whoever will be assembling Sayma 2. The hooks on the brass-colored pins can be manually flared after insertion through the PCB to ensure good grip.

**Comment by gkasprow** [comment]
This is what I meant by the brown plastic things that need to be plugged :)

**Comment by jbqubit** [comment]
I've never seen brown plastic things in connection with the AMC heat sink. On the back side there's just an air gap. The pins are somewhat springy.  

![image](https://user-images.githubusercontent.com/20543958/38116777-8f882990-337f-11e8-9064-f7b611e5a025.png)

**Comment by jbqubit** [comment]
@gkasprow Please close if you've got the information you need from me.
