### ISSUE TITLE
Sayma fix input/output grounding

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#538]
https://github.com/sinara-hw/sinara/issues/499#issuecomment-377071799

**Comment by gkasprow** [comment]
added 100k || 10pF to GND

**Comment by marmeladapk** [comment]
@hartytp Shouldn't it be 0R || 10 pF?

**Comment by hartytp** [comment]
@marmeladapk Yes.

In the original version we used 100k, to help break ground loops. However, we had some bad experiences with Sayma that made us to decide to replace the 100k with 0R.

The thinking is that the default configuration should be to have all grounds tied together. So long as we keep the pads, users can replace 0R with a higher resistance to remove ground currents, however they do that at their own risk!

**Comment by marmeladapk** [comment]
@gkasprow So default configuration is grounded with a note on schematics, that you can unground it.

**Comment by hartytp** [comment]
:+1:
