### ISSUE TITLE
[RFC] use EMC shielded front panels for EEMs

### ISSUE THREAD

**Issue by jordens** [sinara-hw/sinara#549]
They are a about 6-8 € each (including gaskets) and would help when putting EEMs into shielded crates (~130 €). Don't know about secondary effects on the assembly costs though. Needs double checking that the lip doesn't collide with the RJ45/SMA connectors.

**Comment by jordens** [comment]
Pretty sure that the left lip (underside) will touch/collide with the SMAs on Urukul.

**Comment by gkasprow** [comment]
They should fit - of course the THT pins will need to be trimmed.
![obraz](https://user-images.githubusercontent.com/4325054/40613339-72e1221e-627e-11e8-9c53-b87ceee09432.png)

**Comment by jordens** [comment]
That's one solution.
Also that washer under the screw doesn't exist on the boards I have. Might not be needed but it affects clearance.

**Comment by jordens** [comment]
This issue was moved to sinara-hw/meta#2
