### ISSUE TITLE
Sayma sawtooth glitches

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#551]
As requested https://github.com/m-labs/artiq/issues/1022#issuecomment-393850422 differential measurement of sawtooth. 20180530 HMC830 NoSAWG UpdatedJESD 38b51282226f9feb

CH1 and CH2 are externally terminated 50 Ohm. Observe surprising glitches near end of range. Glitches are not coincident in time on differential channels so seems more like a hardware problem than a gateware problem. 

![tek003](https://user-images.githubusercontent.com/20543958/40845980-4367f6d8-6586-11e8-88e0-c6657a8dbb8a.png)
![tek004](https://user-images.githubusercontent.com/20543958/40845981-437277e8-6586-11e8-9bb2-0334cbaed7f7.png)

**Comment by jbqubit** [comment]
This is not a differential probe. Using two channels on scope.

**Comment by jordens** [comment]
The fact that there is about 4ns shift between them is.

**Comment by hartytp** [comment]
fixed by latest JESD204b package. Thanks @enjoy-digital, @jordens and @larsc

**Comment by jbqubit** [comment]
I didn't this fix work. See. https://github.com/sinara-hw/sinara/issues/557#issuecomment-394902405

**Comment by jbqubit** [comment]
I still see a glitch as posted in #557.

**Comment by hartytp** [comment]
If we're talking about the same thing, I was interpreting that as a reflection/SI issue after the sharp rising edge, not a glitch.

**Comment by jbqubit** [comment]
To my eye glitches in this Issue look about the same as reported last night in #557. Glitches are not coincident in time on differential channels neither in this post nor in #557. I don't think this is a problem.

**Comment by hartytp** [comment]
@jbqubit before the recent JESD204B fix, I saw large glitches on the sawtooth generator like https://pasteboard.co/HnSYE20.jpg See https://irclog.whitequark.org/m-labs/2018-06-01 

This wasn't present on all channels and (IIRC) changed from load to load. That's now gone.

**Comment by jbqubit** [comment]
Ok. Let’s keep this closed.
