### ISSUE TITLE
Sayma: check HMC7043 + ramp gen

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#557]
@marmeladapk, @jbqubit I've performed these checks (or similar ones), but it would be great to get results from a different Sayma. After applying the HMC7043 reset fix, please could you:

1. Verify that there are no longer any glitches on the sawtooth produced when Sayma ARTIQ is compiled without the SAWG.
2. Verify that the phase difference between HMC7043 outputs is constant between power cycles/FPGA loads. Use a fast scope and look at the phase difference between: both FPGA clocks (150MHz); the FPGA clock and the SYSREF (9MHz ish); the two SYSREFs; the two DAC clocks; the SYSREF and one DAC clock. In practice, you probably don't need to check all of these, but check a few

If that all looks good then we can verify that JESD is working and that the HMC7043 is operating correctly for SC1 mode.

**Comment by hartytp** [comment]
NB accuracy should be <<1ns so that we can check for phase determinism at the level of a single cycle of the 1.2GHz clock.

**Comment by jbqubit** [comment]
4.0.dev+1117.g38dac160 (today's master) build without SAWG. 

![tek006_000](https://user-images.githubusercontent.com/20543958/41009394-d6753708-68fe-11e8-909a-87cb461f33b6.png)
(above) Differential outputs J26/J27. AC-coupled with external 50-Ohm termination. 

![tek006_001](https://user-images.githubusercontent.com/20543958/41009396-d784e65c-68fe-11e8-84e7-ed2b8223c05c.png)
(above) Differential outputs J26/J27. AC-coupled with external 50-Ohm termination.

**Comment by jbqubit** [comment]
4.0.dev+1117.g38dac160 (today's master) build without SAWG. While waiting for SWAG build to finish. Clock comparison that's possible using RF connectors. Not sure what to expect from J60. 

![tek006_003](https://user-images.githubusercontent.com/20543958/41009673-7dba9f20-6900-11e8-9c40-6bf6f4d7d599.png)
(above) compare DIAG_N (J58) from ADCLK948 with GTP_CLK1_IN (J60)

@hartytp  Which FPGA clocks do you mean? 
- By SYSREF I assume you mean FPGA_DAC_SYSREF
- By DAC clocks I assume you mean DAC1_CLK and DAC2_CLK using scope probe at edge of HMC7043

**Comment by hartytp** [comment]
By FPGA cloxks i mean the 150MHz outputs. Labelled something to do with gtp iirc

**Comment by jbqubit** [comment]
> Labelled something to do with gtp iirc

That's not sufficiently specific.

**Comment by hartytp** [comment]
In what way is that possible not sufficiently specific? 

The HMC7043 has 14 outputs, precisely two of which are labelled something to do with GTP: "GTP_CLK1_IN_{P,N}" and "GTP_CLK2_IN_{P,N}".

You can also look here https://github.com/m-labs/artiq/blob/cae92f9b44d257cfcbb81e38b62408d09972e950/artiq/firmware/libboard_artiq/hmc830_7043.rs#L151-L167

For a listing of what the output frequencies are. To check the "FPGA clocks" look at any pair of enabled outputs that have the divider set to `FPGA_CLK_DIV`, e.g. the GTP clocks, the FPGA aux clocks, etc.

**Comment by jbqubit** [comment]
Wasn't clear if you're interested only in phase stability between outputs on HMC7043 or between HMC7043 and other FPGA-related clocks. What you're after is now clear.

**Comment by hartytp** [comment]
Okay. Yes, the goal is to 

> Verify that the phase difference between HMC7043 outputs is constant between power cycles/FPGA loads.

**Comment by jbqubit** [comment]
Baseline is system that produces RF on all SAWG channels, boots without error and has not generated any panics in several days of regular use. 4.0.dev+1117.g38dac160

Pair of 1 GHz scope probes. Measure skew between rising edges over 10 seconds. Plot as histogram. I can't also capture voltage-vs-time trace while holding scope probes but it appears on screen during measurement. 
- DAC1_CLK (pin 1)
- DAC2_CLK (pin 12) 
- Cycle power on board three times. This generates three histograms.

![tek006_007](https://user-images.githubusercontent.com/20543958/41069129-94f07394-69ba-11e8-94a3-485434583186.png)
![tek006_008](https://user-images.githubusercontent.com/20543958/41069130-94f9e2f8-69ba-11e8-84b8-c59ec66b9594.png)
![tek006_009](https://user-images.githubusercontent.com/20543958/41069131-95081f80-69ba-11e8-842b-de6fd0a155ba.png)

**Comment by hartytp** [comment]
Thanks Joe.

So (with somewhat poor statistics) that verifies that the two DAC clock outputs from the 7043 have deterministic time delays w.r.t. each other to much better than the 800ps period of the 1.2GHz clock.

It would be good to look at the relationship between some other outputs as well, e.g. SYSREF to DAC clock. But, provisionally, that confirms my observation that the HMC7043 is ready for operation of Sayma with deterministic phases between the two DACs on the same Sayma.

**Comment by hartytp** [comment]
@jbqubit @marmeladapk are you planning to take anymore data on this? Otherwise, let's close this issue.

**Comment by marmeladapk** [comment]
@hartytp No, we sent our boards to @jbqubit.

**Comment by jbqubit** [comment]
I don't yet have active differential probes for my scope. So there's most definitely distortion due to my probes. 

# GTP_CLK2_IN (J60) vs FPGA_DAC_SYSREF
The phase skew /looks/ stable for the several minutes I can hold my probes steady.

![tek006_012](https://user-images.githubusercontent.com/20543958/41105834-9ba9ccb2-6a3c-11e8-93c8-1d0b5cfece16.png)

# GTP_CLK1_IN (J60) vs GTP_CLK2_IN
![tek006_010](https://user-images.githubusercontent.com/20543958/41105036-c2efff3c-6a3a-11e8-937c-f7c8dc589e3f.png)
Not sure why there's so much distortion on GTP_CLK2_IN (green). This signal looks much worse than the other clocks coming out of HMC. I don't really trust the histograms here because of the snaggly waveform shape of GTP_CLK2_IN. But by eye the phase skew /looks/ stable for the several minutes I can hold my probes steady.

**Comment by marmeladapk** [comment]
Paging @gkasprow
We have two RTMs, that sometimes don't calibrate DAC sysref correctly. Usually margins on DAC1 are -1 +127 and DAC_SYSREF signals are not in phase (>1 ns of difference). SPI communication seems fine, only there are two moments, where there is a large delay between first 16 bits and last 8.

This is the last issue preventing us from sending fully working Saymas back to UMD.

@sbourdeauducq did you see something like this on your Saymas? If so, how did you deal with it?

**Comment by sbourdeauducq** [comment]
> did you see something like this on your Saymas?

No.

Did you disable RTIO/SYSREF align?

**Comment by marmeladapk** [comment]
@sbourdeauducq Yes.

**Comment by hartytp** [comment]
@marmeladapk I'm pretty sure that the RTM and AMC you returned me were not the ones I sent you. There were a few pieces of undocumented rework I'd done on my boards, such as adding a solder blob on a jumper to fix the JTAG issues, so it's quite inconvenient to get a different board back. Please try to keep track of which board is which...

**Comment by hartytp** [comment]
I also now can't tell whether any new issues are due to me using a different board or for some other reason.
