### ISSUE TITLE
Sayma: AD9154 2X interpolation works

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/sinara#558]
Using 2X interpolation on AD9154 and 2400 MHz DAC clock from HMC7043. Firmware changes

1) activate 2X interpolation 
ad9154.rs 
    INTERP_MODE, 0x01  for 2X 

2) double DAC clock 
hmc830_7043.rs 
    const DAC_CLK_DIV: u32 = 1; 

As far as I can tell this just works. 

sawg.frequency0.set(210*MHz) 
sawg.frequency1.set(50*MHz) 

#  1X interpolation 
![image](https://user-images.githubusercontent.com/20543958/41207182-11749626-6cdf-11e8-8ccb-ffcfc0335630.png)

#  2X interpolation 
![image](https://user-images.githubusercontent.com/20543958/41207186-1b1cc004-6cdf-11e8-90f7-8214fb509638.png)

**Comment by jbqubit** [comment]
This is a good news Issue. Thanks for the tip @hartytp!

**Comment by jbqubit** [comment]
```
sawg.frequency0.set(210*MHz)
sawg.frequency1.set(-50*MHz)
sawg.frequency2.set(50*MHz)
```


![print_001](https://user-images.githubusercontent.com/20543958/41207776-5422ce2a-6ce9-11e8-9e65-9344c32ff0da.PNG)

**Comment by hartytp** [comment]
Nice! Glad some things on Sayma just work.
