### ISSUE TITLE
Sayma: HMC830 output spectrum

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#560]
- [x] To do: check HMC830 noise spectrum

With current ARTIQ master (4.0.dev+1133.g0b086225), looking at J89 + J59 through an AC-coupled TCM-43X+, I see:

![20180611_094239](https://user-images.githubusercontent.com/21218399/41221825-35ee65d0-6d5d-11e8-8df0-587205e26231.jpg)

Wide span (10kHz RBW). All looks good apart from the non-harmonic spur at 1.89GHz something like -60dBc.

![20180611_094454](https://user-images.githubusercontent.com/21218399/41221860-4f6a567c-6d5d-11e8-93be-080a325c1720.jpg)
Narrower span, including fundamental and first harmonic.

![20180611_094908](https://user-images.githubusercontent.com/21218399/41221888-6479fc20-6d5d-11e8-8c9b-75afcadfbd1a.jpg)
1MHz span around fundamental, 100Hz RBW. See some spurs at around 100kHz. I think these are SMPS spurs. @gkasprow can you confirm that? May need better power supply filtering or a layout tweak to remove them.

**Comment by hartytp** [comment]
The 1.9GHz spur is still there while the board is being flashed and no clock is applied.

**Comment by hartytp** [comment]
@gkasprow this could be some clock chip free oscillating without an input applied. I don't have fast enough scope probes to easily find that. Would you mind taking a look?

Thanks!

**Comment by hartytp** [comment]
Oh, I think I know what this is... those clock chips are so damn fast that the put out a frequency comb up to pretty much optical frequencies.

I'm pretty sure that this is the 19th harmonic of the 100MHz reference input that's not perfectly removed by the loop filter! Wow...

Fixes for this are:
1. Add a RF filter on the PLL input to slightly reduce the rise time of the signal, while keeping it above 1V/ns
2. Add a higher-order loop filter/some RFI filtering on the loop filter.

**Comment by jordens** [comment]
I'd expect to see other harmonics as well then.

**Comment by hartytp** [comment]
True.

Well, anyway, this is probably something which @gkasprow or @marmeladapk are the best people to investigate...

**Comment by hartytp** [comment]
Actually, on second thoughts, it can't be that, as it's still there with the clock disconnected. So, probably is just an oscillating clock buffer. Anyway, should be easy for someone with proper GHz probes to track down.

**Comment by hartytp** [comment]
Here is a NSD measurement of the HMC830 output.

![figure_1](https://user-images.githubusercontent.com/21218399/41282931-30fa0068-6e2d-11e8-8e4c-557b6aadf996.png)

Simulation: 

https://cloud.githubusercontent.com/assets/21218399/20439893/a9a4e080-adb5-11e6-835f-7a54faac60f3.png

Notes:
- RBW is 10Hz, so subtracting 10dB from power measurement to convert to NSD (not bothering about various correction factors due to windows etc)
- Freq is 1.2GHz, so subtracting `20*np.log10(1200/100)=21.6dB` to normalize to 10MHz
- Simulation issue is https://github.com/sinara-hw/sinara/issues/75

**Comment by hartytp** [comment]
So, this actually looks pretty good apart from the SMPS spurs...

**Comment by hartytp** [comment]
Edit: updated figure above after fixing normalisation issue...

**Comment by hartytp** [comment]
@gkasprow can you see if you can figure out where those spurs are coming from and how they couple in (power lines? pickup? noise in the ground plane?)

NB I see quite a bit of SMPS noise on the HMC7043 outputs even when they're muted, so I think there is an issue that needs to be looked at there!

**Comment by hartytp** [comment]
![figure_1](https://user-images.githubusercontent.com/21218399/41286816-b308d9d4-6e38-11e8-8748-37f62f4e0756.png)

HMC7043 GTP_CLK1 (J60 and J61) at 150MHz.

**Comment by hartytp** [comment]
Same as before, but now a 1GHz span.

![figure_1](https://user-images.githubusercontent.com/21218399/41288663-03a27890-6e3f-11e8-89c1-ed6ca27b978e.png)

**Comment by hartytp** [comment]
![figure_1](https://user-images.githubusercontent.com/21218399/41291240-09d851be-6e47-11e8-9ea7-521189c56963.png)

still looking at GTX_CLK1 TPs, but this time with 150MHz outputs. RBW=1kHz and (hopefully) the correct normalization this time...

**Comment by hartytp** [comment]
Now, looking at my 100MHz reference on the MEZ_CLK_IN SMPs.

Wide scan, 1kHz RBW.

![figure_1](https://user-images.githubusercontent.com/21218399/41294231-6cc9f4be-6e4f-11e8-99f5-ab1a0c436d5f.png)

**Comment by hartytp** [comment]
5MHz span, 10Hz RBW, still looking at 100MHz reference on SMPs

![figure_1](https://user-images.githubusercontent.com/21218399/41295393-6aa4b5cc-6e52-11e8-8f27-c8b59dbb788f.png)

**Comment by hartytp** [comment]
Same, but putting my synth directly on the spectrum analyzer. Note that only the left section of the measurement completed (the data taking takes an age and I got impatient, the rhs is a previous measurement).

![figure_1](https://user-images.githubusercontent.com/21218399/41295751-3db9d73a-6e53-11e8-807d-006c95db6c4d.png)

So, a lot of what I see above is due to the synth I'm using as my clock source, which has worse spurs than I remembered.

**Comment by hartytp** [comment]
Anyway, so far, Sayma looks excellent noise-wise. We should put it on a proper phase noise metre at some point to get better data.

**Comment by hartytp** [comment]
Looking on the SMPs at 1.89GHz/12=157.5MHz, I don't see anything with or without my clock source applied. Same at 1.89GHz (although, I do obviously see a 1.9GHz harmonic of the squared reference). I'm no longer seeing the 1.89GHz spur on the HMC830 output. Not sure what happened (measurement error? something coming out of lock?)

Anyway, that concludes these measurements for now. 

tk;dr: looks good! But, needs more careful measurements with the proper equipment.

**Comment by hartytp** [comment]
okay, the 1.89GHz is just lab pickup...

**Comment by hartytp** [comment]
Posting this here for want of a better place...

Here is the SAWG output at 210MHz, as measured from the SMPs via an AC-coupled balun (TCM2-43X+). Using same clock source as above...

![figure_1](https://user-images.githubusercontent.com/21218399/41343961-da8d9e44-6ef7-11e8-913e-956fb2711504.png)

**Comment by hartytp** [comment]
10Hz RBW, narrower span, still in power units.
[sawg_narrow.txt](https://github.com/sinara-hw/sinara/files/2097794/sawg_narrow.txt)

![figure_1](https://user-images.githubusercontent.com/21218399/41346906-f8f5460e-6eff-11e8-9e82-bc6fe8af3245.png)

**Comment by hartytp** [comment]
Same, but plotted in PSD units.
![figure_1](https://user-images.githubusercontent.com/21218399/41347006-4777b5be-6f00-11e8-96ca-07edc92f0c7c.png)
