### ISSUE TITLE
Sayma AMC: fix FPGA VCCINT supply

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/sinara#566]
c.f. https://github.com/m-labs/artiq/issues/1065

* VCCINT setpoint too low
* VCCINT unstable and dropping under load

Note that we envision an increased FPGA consumption as more ARTIQ/SAWG features are added, so the VCCINT drop should be well understood and properly fixed.

**Comment by gkasprow** [comment]
fixed 
![obraz](https://user-images.githubusercontent.com/4325054/49118947-b2058800-f2a6-11e8-82f8-0810178d27e0.png)

**Comment by marmeladapk** [comment]
VCCINT is set to ~0,95 V + feedback is from under FPGA. @sbourdeauducq is that fine?

**Comment by sbourdeauducq** [comment]
Assuming we use the -1 speed grade, 0.95V is the nominal value from the datasheet.
The PCB layout should be carefully simulated and reviewed, perhaps by at least two independent people. On Sayma v1, Greg's simulation results were wrong (Xilinx tech support ran the simulation again and found issues), the load-dependent voltage drop was excessive, and this contributed to the "SAWG crashes/HMC7043 noise/SDRAM" bug saga.

**Comment by sbourdeauducq** [comment]
"
In offline discussion @sbourdeauducq asked...

```
One thing about the power supply: can we run the PCB layout by the 
Xilinx engineers like last time, and have them cross-check the DC drop 
simulation results before PCB production, for both Sayma and Metlino? It 
would be a shame if this problem comes to bite us again.
```

In offline discussion 2/21 @gkasprow responded

`I will publish simulation sources and results so it would take a moment for Xilinx team to review it.`

In offline discussion 2/21 @gkasprow noted

```
I finally found what was a problem with DC drop. It was not really 
caused by the wrong simulation but by the fact that the PCB 
workshop increased clearances around the vias which caused DRC increase 
of the supply plane. Another issue was missing compensation resistor.
```
"
