### ISSUE TITLE
HMC830 does not lock when driven by AMC clock output

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/sinara#573]
The clock output from AMC looks OK:
![tek00147](https://user-images.githubusercontent.com/4325054/43776327-c5b3b71e-9a4f-11e8-93fc-c493dee6071e.png)

**Comment by gkasprow** [comment]
But when I connect it to the RTM the signal disappears....
This is a reason why - the input SMA has shorted pin to GND.
When I connect it with AMC, the HMC locks and PRBS errors disappear...

**Comment by sbourdeauducq** [comment]
I don't understand that. Where is the short circuit and how do you make it disappear?
What does this have to do with PRBS?

**Comment by gkasprow** [comment]
it is at the RTM SMA clock input.
Since it was shorted, the clock signal entering the RTM board had very low amplitude. And that's why in your conditions HMC830 could not lock. In my lab it locks probably because I have very strong 100MHz signal source outside (FM broadcast station a few hundreds meters from me) so the RTM could pickup the signal and together with leaking generator signal the HMC managed to lock to it :)
But the quality of recovered signal was not enough for transcivers

**Comment by hartytp** [comment]
hmmm...on my RTM the clock SMA input is a high impedance between the signal pin and ground. Moreover, if you look at the traces I've posted, the HMC830 clock output is very high quality (at least, as far as I can tell from a SA). So, I don't think this was a problem on my board.

**Comment by hartytp** [comment]
Also, on my board, CLK1 works reliably and CLK2 doesn't.

**Comment by gkasprow** [comment]
So it looks like there is sth else on your board.
If you want, I can post you my set of boards and you will post me your one.

**Comment by hartytp** [comment]
@gkasprow after fixing that, does the PRBS work on all of your AMC/RTM combinations? If so, that's great!

**Comment by gkasprow** [comment]
I tested with 5 RTM boards and clocking from AMC board works fine.

**Comment by gkasprow** [comment]
I have 5 sets of boards so there is quite a lot of combinations to tests :)

**Comment by hartytp** [comment]
> I have 5 sets of boards so there is quite a lot of combinations to tests :)

Sure. I'd pick 1 RTM and check it with all AMCs. Then pick one AMC and check with all RTMs. If that looks good, it suggests that the issue only lies with particular boards. If that's the case, the best thing is for me to post you both my AMC and RTM and you can look at this particular pair.

**Comment by gkasprow** [comment]
I made 5 sets of random boards and will test them together.

**Comment by gkasprow** [comment]
OK, i'm testingt all 25 combinations to be sure.

**Comment by gkasprow** [comment]
one combination causes HMC830 lock failure...

**Comment by sbourdeauducq** [comment]
> OK, i'm testing all 25 combinations to be sure.
> one combination causes HMC830 lock failure...

I'm glad you are finally starting to get into the Sayma mess...

**Comment by gkasprow** [comment]
this AMC is missing rework at the clock buffer IC...

**Comment by hartytp** [comment]
> this AMC is missing rework at the clock buffer IC...

What rework is that?

**Comment by sbourdeauducq** [comment]
> it is at the RTM SMA clock input.
> Since it was shorted,

Where was that short?

**Comment by gkasprow** [comment]
rework around IC40. Pins 7 and 12 must be grounded. IC need to be desoldered, traces to pins 7 and 12 cut and with piece of wire connected to nearby capacitor.

**Comment by gkasprow** [comment]
@sbourdeauducq the short was just at the board edge.

**Comment by sbourdeauducq** [comment]
So it's a hard short, i.e. something I can check easily with just a DC ohmmeter?

**Comment by gkasprow** [comment]
yes

**Comment by hartytp** [comment]
> rework around IC40. Pins 7 and 12 must be grounded. IC need to be desoldered, traces to pins 7 and 12 cut and with piece of wire connected to nearby capacitor.

I don't see that on my board. Do you have a photo?

**Comment by sbourdeauducq** [comment]
> yes

OK. One of the last RTM you sent me stopped locking after I fiddled with it, so that may be the problem...

**Comment by gkasprow** [comment]
it's quite possible that the SMA lost contact with trace

**Comment by hartytp** [comment]
Yes, but you can see that clearly with a scope...

**Comment by sbourdeauducq** [comment]
The constant stream of problems that Sayma has with just about everything makes my mind boggle. I haven't seen any shorted or broken SMA on any of the DIO and Urukul cards that I've tested. That's almost 200 SMAs and they were all good. What is going on with Sayma?

**Comment by hartytp** [comment]
is's a more delicate, more complicated design that has been heavily reworked. Once we stop poking it and put it in a uTCA rack where it belongs, we won't see these kinds of issues.

**Comment by gkasprow** [comment]
It was only one shorted connector so far. It was shorted during assembly.
 Sayma is far more complex than any other 3U board. All the EEM boards together have such complexity as Sayma. So if you compare all issues related with EEMs with all Sayma issues the results will be similar :)

**Comment by hartytp** [comment]
Also, @sbourdeauducq while people are working hard to fix problems, let's channel our energy towards focused comments/bug hunting rather than general moaning.

**Comment by gkasprow** [comment]
OK, so I tested all 25 combinations. All work fine with AMC -> RTM clocking..

**Comment by gkasprow** [comment]
The only difference is number of STPL errors that on some boards combinations appear...

**Comment by hartytp** [comment]
@gkasprow That's great. So, all boards now lock and pass PRBS tests now apart from my board?

Can you post a picture of the IC40 rework that was missing on one board? If it's missing on mine, I'll do it myself. Otherwise, I'll post the board back to you for investigation.

Also, can you remind me which version of ARTIQ you're testing (maybe post a UART output with the version information)? Make sure you're not testing with the latest ARTIQ as @sbourdeauducq pushed a commit that changed the clock configuration to avoid using the problematic CLK2 input.

**Comment by gkasprow** [comment]
I'm testing 
[     0.003883s]  INFO(runtime): software ident 4.0.dev+1286.g015c592a;standalone
[     0.011017s]  INFO(runtime): gateware ident 4.0.dev+1286.g015c592a;standalone

**Comment by gkasprow** [comment]
@hartytp 
![obraz](https://user-images.githubusercontent.com/4325054/43784943-9b37fde0-9a65-11e8-97fa-6fb0c3d1fa71.png)

**Comment by hartytp** [comment]
Okay, that's really quite old, but I think it should be fine. @sbourdeauducq are you happy using this for testing? NB this is before we disabled the unused LVPECL HMC7043 outputs, so it's nice to see that those don't actually cause an issue.

**Comment by gkasprow** [comment]
IC40 is locted above FPGA, between FPGA and FMC

**Comment by hartytp** [comment]
Oh, you mean on the AMC. Okay, mine does have that rework.

Okay, well let me send you my AMC + RTM back for investigation. I'll leave a version of ARTIQ flashed on them that exhibits this bug.
