### ISSUE TITLE
remove Si5324 to HMC830 connection/mux on the RTM

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/sinara#582]
https://github.com/sinara-hw/sinara/issues/576#issuecomment-412284694

**Comment by gkasprow** [comment]
removed, together with mux.
@hartytp what we do with LO signal routing to all mezzanines?

**Comment by hartytp** [comment]
@gkasprow On Sayma v2.0 there will not be a LO generated on the RTM because there will not be a clock mezzanine.

The plan is to route the reference to each AFE. The AFEs can then have a PLL if required.

**Comment by gkasprow** [comment]
you mean 100MHz reference we get from SMA input?

**Comment by hartytp** [comment]
@gkasprow it will usually be 125MHz in v2.0 to make the synchronisation easier, but yes, that's what I mean.

**Comment by gkasprow** [comment]
We will use ADCLK948 for reception of SMA ref signal and distribution of it to mezzanines (LO signal) so we can leave Si5324 connection to ADCLK948 with no cost.

**Comment by marmeladapk** [comment]
I guess this issue can be closed. Added benefit of keeping this connection is that we can use WR clock if we decide to implement it on RTM.
