### ISSUE TITLE
sayma: sysref coupling + termination

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/sinara#588]
Sysref should be DC coupled and 50Ohm terminated at the DAC. Currently, it's AC coupled and untermianted (AFAICT, the DAC sysref inputs are high-Z).

**Comment by hartytp** [comment]
NB need to be careful with the logic level conversion here since the optimal common-mode voltage for the SYSREF inputs is 600mV. So, need a resistor network to match that to the LVPECL/CML/whatever driver.

NB in my tests, I'm using AC-coupled LVPECL since it would be very tough to add such a network to Sayma (too fine pitch everywhere, no convenient access to ground, etc).

**Comment by gkasprow** [comment]
It's easier to remove terminating resistors and switch to LVDS mode. At the moment the termination resistors are soldered directly to the DAC pins. AFAIR I did it not only for clock but also for sysref inputs.

**Comment by marmeladapk** [comment]
@gkasprow @hartytp What is the conclusion here? In schematics SYSREF is AC coupled, has 100R differential termination and 200R to ground at source.

Source:
![obraz](https://user-images.githubusercontent.com/24512604/50899820-8df3a580-1413-11e9-92e2-9c40df28ff53.png)
DAC:
![obraz](https://user-images.githubusercontent.com/24512604/50899842-9ba92b00-1413-11e9-920b-63887d87088f.png)

**Comment by hartytp** [comment]
Closing in favour of https://github.com/sinara-hw/Sayma_RTM/issues/13

**Comment by gkasprow** [comment]
200R is pulldown for open emitter outputs. 100R is differential termination. Such a solution consumes far less power than Thevenin termination.
